PRAGMA foreign_keys = ON;

CREATE TABLE
    IF NOT EXISTS USER_DETAILS (
        USER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        USERNAME VARCHAR NOT NULL,
        PASSWORD VARCHAR NOT NULL,
        EMAIL TEXT NOT NULL UNIQUE
    );

CREATE TABLE
    IF NOT EXISTS USER_PROFILE (
        USER_ID INTEGER PRIMARY KEY,
        IS_ACTIVE BOOLEAN,
        CONSTRAINT FK_UP_UD FOREIGN KEY (USER_ID) REFERENCES USER_DETAILS (USER_ID)
    );

CREATE TABLE
    IF NOT EXISTS CUSTOMER (
        CUSTOMER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        CUSTOMER_NAME VARCHAR NOT NULL,
        CUSTOMER_ADDRESS VARCHAR NOT NULL,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UPDATED_AT TIMESTAMP
    );

CREATE TABLE
    IF NOT EXISTS CUSTOMER_PROFILE (
        CUSTOMER_ID INTEGER PRIMARY KEY,
        IS_ACTIVE BOOLEAN,
        ROLE VARCHAR NOT NULL,
        CONSTRAINT FK_CP_CU FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID)
    );

CREATE TABLE
    IF NOT EXISTS ORDERS (
        ORDER_ID VARCHAR PRIMARY KEY,
        DESCRIPTION VARCHAR,
        PRICE DECIMAL,
        CUSTOMER_ID INTEGER NOT NULL,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UPDATED_AT TIMESTAMP,
        CONSTRAINT FK_O_C FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID)
    );

CREATE TABLE
    IF NOT EXISTS ORDER_ITEM (
        ITEM_ID INTEGER PRIMARY KEY AUTOINCREMENT,
        QUANTITY INTEGER DEFAULT 1,
        PRODUCT_NAME VARCHAR,
        PRODUCT_TYPE VARCHAR,
        UNIT_PRICE DECIMAL,
        ORDER_ID INTEGER NOT NULL,
        CONSTRAINT FK_OI_O FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID)
    );