CREATE TABLE
    IF NOT EXISTS USER_DETAILS (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        USERNAME VARCHAR NOT NULL,
        PASSWORD VARCHAR NOT NULL,
        EMAIL TEXT NOT NULL UNIQUE
    );